package com.cuongnl.ridehailing.enums

import com.cuongnl.ridehailing.R

enum class CountryCode(
    val countryFlag: Int,
    val countryName: String,
    val phoneCode: String,
    val minLength: Int = 3,
    val maxLength: Int = 20
) {
    AFGHANISTAN(R.drawable.flag_af, "Afghanistan", "+93"),
    ALBANIA(R.drawable.flag_al, "Albania", "+355"),
    ALGERIA(R.drawable.flag_dz, "Algeria", "+213"),
    AMERICAN_SAMOA(R.drawable.flag_as, "American Samoa", "+1684"),
    ANDORRA(R.drawable.flag_ad, "Andorra", "+376"),
    ANGOLA(R.drawable.flag_ao, "Angola", "+244"),
    ANGUILLA(R.drawable.flag_ai, "Anguilla", "+1264"),
    ANTARCTICA(R.drawable.flag_aq, "Antarctica", "+672"),
    ANTIGUA_AND_BARBUDA(R.drawable.flag_ag, "Antigua and Barbuda", "+1268"),
    ARGENTINA(R.drawable.flag_ar, "Argentina", "+54"),
    ARMENIA(R.drawable.flag_am, "Armenia", "+374"),
    ARUBA(R.drawable.flag_aw, "Aruba", "+297"),
    AUSTRALIA(R.drawable.flag_au, "Australia", "+61"),
    AUSTRIA(R.drawable.flag_at, "Austria", "+43"),
    AZERBAIJAN(R.drawable.flag_az, "Azerbaijan", "+994"),
    BAHAMAS(R.drawable.flag_bs, "Bahamas", "+1242"),
    BAHRAIN(R.drawable.flag_bh, "Bahrain", "+973"),
    BANGLADESH(R.drawable.flag_bd, "Bangladesh", "+880"),
    BARBADOS(R.drawable.flag_bb, "Barbados", "+1246"),
    BELARUS(R.drawable.flag_by, "Belarus", "+375"),
    BELGIUM(R.drawable.flag_be, "Belgium", "+32"),
    BELIZE(R.drawable.flag_bz, "Belize", "+501"),
    BENIN(R.drawable.flag_bj, "Benin", "+229"),
    BERMUDA(R.drawable.flag_bm, "Bermuda", "+1441"),
    BHUTAN(R.drawable.flag_bt, "Bhutan", "+975"),
    BOLIVIA(R.drawable.flag_bo, "Bolivia", "+591"),
    BOSNIA_AND_HERZEGOVINA(R.drawable.flag_ba, "Bosnia and Herzegovina", "+387"),
    BOTSWANA(R.drawable.flag_bw, "Botswana", "+267"),
    BRAZIL(R.drawable.flag_br, "Brazil", "+55"),
    BRITISH_INDIAN_OCEAN_TERRITORY(R.drawable.flag_io, "British Indian Ocean Territory", "+246"),
    BRITISH_VIRGIN_ISLANDS(R.drawable.flag_vg, "British Virgin Islands", "+1284"),
    BRUNEI(R.drawable.flag_bn, "Brunei", "+673"),
    BULGARIA(R.drawable.flag_bg, "Bulgaria", "+359"),
    BURKINA_FASO(R.drawable.flag_bf, "Burkina Faso", "+226"),
    BURUNDI(R.drawable.flag_bi, "Burundi", "+257"),
    CAMBODIA(R.drawable.flag_kh, "Cambodia", "+855"),
    CAMEROON(R.drawable.flag_cm, "Cameroon", "+237"),
    CANADA(R.drawable.flag_ca, "Canada", "+1"),
    CAPE_VERDE(R.drawable.flag_cv, "Cape Verde", "+238"),
    CAYMAN_ISLANDS(R.drawable.flag_ky, "Cayman Islands", "+1345"),
    CENTRAL_AFRICAN_REPUBLIC(R.drawable.flag_cf, "Central African Republic", "+236"),
    CHAD(R.drawable.flag_td, "Chad", "+235"),
    CHILE(R.drawable.flag_cl, "Chile", "+56"),
    CHINA(R.drawable.flag_cn, "China", "+86"),
    CHRISTMAS_ISLAND(R.drawable.flag_cx, "Christmas Island", "+61"),
    COCOS_ISLANDS(R.drawable.flag_cc, "Cocos Islands", "+61"),
    COLOMBIA(R.drawable.flag_co, "Colombia", "+57"),
    COMOROS(R.drawable.flag_km, "Comoros", "+269"),
    COOK_ISLANDS(R.drawable.flag_ck, "Cook Islands", "+682"),
    COSTA_RICA(R.drawable.flag_cr, "Costa Rica", "+506"),
    CROATIA(R.drawable.flag_hr, "Croatia", "+385"),
    CUBA(R.drawable.flag_cu, "Cuba", "+53"),
    CURACAO(R.drawable.flag_cw, "Curacao", "+599"),
    CYPRUS(R.drawable.flag_cy, "Cyprus", "+357"),
    CZECH_REPUBLIC(R.drawable.flag_cz, "Czech Republic", "+420"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO(R.drawable.flag_cd, "Democratic Republic of the Congo", "+243"),
    DENMARK(R.drawable.flag_dk, "Denmark", "+45"),
    DJIBOUTI(R.drawable.flag_dj, "Djibouti", "+253"),
    DOMINICA(R.drawable.flag_dm, "Dominica", "+1767"),
    DOMINICAN_REPUBLIC(R.drawable.flag_do, "Dominican Republic", "+1809"),
    EAST_TIMOR(R.drawable.flag_tl, "East Timor", "+670"),
    ECUADOR(R.drawable.flag_ec, "Ecuador", "+593"),
    EGYPT(R.drawable.flag_eg, "Egypt", "+20"),
    EL_SALVADOR(R.drawable.flag_sv, "El Salvador", "+503"),
    EQUATORIAL_GUINEA(R.drawable.flag_gq, "Equatorial Guinea", "+240"),
    ERITREA(R.drawable.flag_er, "Eritrea", "+291"),
    ESTONIA(R.drawable.flag_ee, "Estonia", "+372"),
    ETHIOPIA(R.drawable.flag_et, "Ethiopia", "+251"),
    FALKLAND_ISLANDS(R.drawable.flag_fk, "Falkland Islands", "+500"),
    FAROE_ISLANDS(R.drawable.flag_fo, "Faroe Islands", "+298"),
    FIJI(R.drawable.flag_fj, "Fiji", "+679"),
    FINLAND(R.drawable.flag_fi, "Finland", "+358"),
    FRANCE(R.drawable.flag_fr, "France", "+33"),
    FRENCH_POLYNESIA(R.drawable.flag_pf, "French Polynesia", "+689"),
    GABON(R.drawable.flag_ga, "Gabon", "+241"),
    GAMBIA(R.drawable.flag_gm, "Gambia", "+220"),
    GEORGIA(R.drawable.flag_ge, "Georgia", "+995"),
    GERMANY(R.drawable.flag_de, "Germany", "+49"),
    GHANA(R.drawable.flag_gh, "Ghana", "+233"),
    GIBRALTAR(R.drawable.flag_gi, "Gibraltar", "+350"),
    GREECE(R.drawable.flag_gr, "Greece", "+30"),
    GREENLAND(R.drawable.flag_gl, "Greenland", "+299"),
    GRENADA(R.drawable.flag_gd, "Grenada", "+1473"),
    GUAM(R.drawable.flag_gu, "Guam", "+1671"),
    GUATEMALA(R.drawable.flag_gt, "Guatemala", "+502"),
    GUERNSEY(R.drawable.flag_gg, "Guernsey", "+44"),
    GUINEA(R.drawable.flag_gn, "Guinea", "+224"),
    GUINEA_BISSAU(R.drawable.flag_gw, "Guinea-Bissau", "+245"),
    GUYANA(R.drawable.flag_gy, "Guyana", "+592"),
    HAITI(R.drawable.flag_ht, "Haiti", "+509"),
    HONDURAS(R.drawable.flag_hn, "Honduras", "+504"),
    HONG_KONG(R.drawable.flag_hk, "Hong Kong", "+852"),
    HUNGARY(R.drawable.flag_hu, "Hungary", "+36"),
    ICELAND(R.drawable.flag_is, "Iceland", "+354"),
    INDIA(R.drawable.flag_in, "India", "+91"),
    INDONESIA(R.drawable.flag_id, "Indonesia", "+62"),
    IRAN(R.drawable.flag_ir, "Iran", "+98"),
    IRAQ(R.drawable.flag_iq, "Iraq", "+964"),
    IRELAND(R.drawable.flag_ie, "Ireland", "+353"),
    ISLE_OF_MAN(R.drawable.flag_im, "Isle of Man", "+44"),
    ISRAEL(R.drawable.flag_il, "Israel", "+972"),
    ITALY(R.drawable.flag_it, "Italy", "+39"),
    IVORY_COAST(R.drawable.flag_ci, "Ivory Coast", "+225"),
    JAMAICA(R.drawable.flag_jm, "Jamaica", "+1876"),
    JAPAN(R.drawable.flag_jp, "Japan", "+81"),
    JERSEY(R.drawable.flag_je, "Jersey", "+44"),
    JORDAN(R.drawable.flag_jo, "Jordan", "+962"),
    KAZAKHSTAN(R.drawable.flag_kz, "Kazakhstan", "+7"),
    KENYA(R.drawable.flag_ke, "Kenya", "+254"),
    KIRIBATI(R.drawable.flag_ki, "Kiribati", "+686"),
    KOSOVO(R.drawable.flag_xk, "Kosovo", "+383"),
    KUWAIT(R.drawable.flag_kw, "Kuwait", "+965"),
    KYRGYZSTAN(R.drawable.flag_kg, "Kyrgyzstan", "+996"),
    LAOS(R.drawable.flag_la, "Laos", "+856"),
    LATVIA(R.drawable.flag_lv, "Latvia", "+371"),
    LEBANON(R.drawable.flag_lb, "Lebanon", "+961"),
    LESOTHO(R.drawable.flag_ls, "Lesotho", "+266"),
    LIBERIA(R.drawable.flag_lr, "Liberia", "+231"),
    LIBYA(R.drawable.flag_ly, "Libya", "+218"),
    LIECHTENSTEIN(R.drawable.flag_li, "Liechtenstein", "+423"),
    LITHUANIA(R.drawable.flag_lt, "Lithuania", "+370"),
    LUXEMBOURG(R.drawable.flag_lu, "Luxembourg", "+352"),
    MACAU(R.drawable.flag_mo, "Macau", "+853"),
    MACEDONIA(R.drawable.flag_mk, "Macedonia", "+389"),
    MADAGASCAR(R.drawable.flag_mg, "Madagascar", "+261"),
    MALAWI(R.drawable.flag_mw, "Malawi", "+265"),
    MALAYSIA(R.drawable.flag_my, "Malaysia", "+60"),
    MALDIVES(R.drawable.flag_mv, "Maldives", "+960"),
    MALI(R.drawable.flag_ml, "Mali", "+223"),
    MALTA(R.drawable.flag_mt, "Malta", "+356"),
    MARSHALL_ISLANDS(R.drawable.flag_mh, "Marshall Islands", "+692"),
    MAURITANIA(R.drawable.flag_mr, "Mauritania", "+222"),
    MAURITIUS(R.drawable.flag_mu, "Mauritius", "+230"),
    MAYOTTE(R.drawable.flag_yt, "Mayotte", "+262"),
    MEXICO(R.drawable.flag_mx, "Mexico", "+52"),
    MICRONESIA(R.drawable.flag_fm, "Micronesia", "+691"),
    MOLDOVA(R.drawable.flag_md, "Moldova", "+373"),
    MONACO(R.drawable.flag_mc, "Monaco", "+377"),
    MONGOLIA(R.drawable.flag_mn, "Mongolia", "+976"),
    MONTENEGRO(R.drawable.flag_me, "Montenegro", "+382"),
    MONTSERRAT(R.drawable.flag_ms, "Montserrat", "+1664"),
    MOROCCO(R.drawable.flag_ma, "Morocco", "+212"),
    MOZAMBIQUE(R.drawable.flag_mz, "Mozambique", "+258"),
    MYANMAR(R.drawable.flag_mm, "Myanmar", "+95"),
    NAMIBIA(R.drawable.flag_na, "Namibia", "+264"),
    NAURU(R.drawable.flag_nr, "Nauru", "+674"),
    NEPAL(R.drawable.flag_np, "Nepal", "+977"),
    NETHERLANDS(R.drawable.flag_nl, "Netherlands", "+31"),
    NEW_CALEDONIA(R.drawable.flag_nc, "New Caledonia", "+687"),
    NEW_ZEALAND(R.drawable.flag_nz, "New Zealand", "+64"),
    NICARAGUA(R.drawable.flag_ni, "Nicaragua", "+505"),
    NIGER(R.drawable.flag_ne, "Niger", "+227"),
    NIGERIA(R.drawable.flag_ng, "Nigeria", "+234"),
    NIUE(R.drawable.flag_nu, "Niue", "+683"),
    NORTH_KOREA(R.drawable.flag_kp, "North Korea", "+850"),
    NORTHERN_MARIANA_ISLANDS(R.drawable.flag_mp, "Northern Mariana Islands", "+1670"),
    NORWAY(R.drawable.flag_no, "Norway", "+47"),
    OMAN(R.drawable.flag_om, "Oman", "+968"),
    PAKISTAN(R.drawable.flag_pk, "Pakistan", "+92"),
    PALAU(R.drawable.flag_pw, "Palau", "+680"),
    PALESTINE(R.drawable.flag_ps, "Palestine", "+970"),
    PANAMA(R.drawable.flag_pa, "Panama", "+507"),
    PAPUA_NEW_GUINEA(R.drawable.flag_pg, "Papua New Guinea", "+675"),
    PARAGUAY(R.drawable.flag_py, "Paraguay", "+595"),
    PERU(R.drawable.flag_pe, "Peru", "+51"),
    PHILIPPINES(R.drawable.flag_ph, "Philippines", "+63"),
    PITCAIRN(R.drawable.flag_pn, "Pitcairn", "+64"),
    POLAND(R.drawable.flag_pl, "Poland", "+48"),
    PORTUGAL(R.drawable.flag_pt, "Portugal", "+351"),
    PUERTO_RICO(R.drawable.flag_pr, "Puerto Rico", "+1787"),
    QATAR(R.drawable.flag_qa, "Qatar", "+974"),
    REPUBLIC_OF_THE_CONGO(R.drawable.flag_cg, "Republic of the Congo", "+242"),
    REUNION(R.drawable.flag_re, "Reunion", "+262"),
    ROMANIA(R.drawable.flag_ro, "Romania", "+40"),
    RUSSIA(R.drawable.flag_ru, "Russia", "+7"),
    RWANDA(R.drawable.flag_rw, "Rwanda", "+250"),
    SAINT_BARTHELEMY(R.drawable.flag_bl, "Saint Barthelemy", "+590"),
    SAINT_HELENA(R.drawable.flag_sh, "Saint Helena", "+290"),
    SAINT_KITTS_AND_NEVIS(R.drawable.flag_kn, "Saint Kitts and Nevis", "+1869"),
    SAINT_LUCIA(R.drawable.flag_lc, "Saint Lucia", "+1758"),
    SAINT_MARTIN(R.drawable.flag_mf, "Saint Martin", "+590"),
    SAINT_PIERRE_AND_MIQUELON(R.drawable.flag_pm, "Saint Pierre and Miquelon", "+508"),
    SAINT_VINCENT_AND_THE_GRENADINES(R.drawable.flag_vc, "Saint Vincent and the Grenadines", "+1784"),
    SAMOA(R.drawable.flag_ws, "Samoa", "+685"),
    SAN_MARINO(R.drawable.flag_sm, "San Marino", "+378"),
    SAO_TOME_AND_PRINCIPE(R.drawable.flag_st, "Sao Tome and Principe", "+239"),
    SAUDI_ARABIA(R.drawable.flag_sa, "Saudi Arabia", "+966"),
    SENEGAL(R.drawable.flag_sn, "Senegal", "+221"),
    SERBIA(R.drawable.flag_rs, "Serbia", "+381"),
    SEYCHELLES(R.drawable.flag_sc, "Seychelles", "+248"),
    SIERRA_LEONE(R.drawable.flag_sl, "Sierra Leone", "+232"),
    SINGAPORE(R.drawable.flag_sg, "Singapore", "+65"),
    SINT_MAARTEN(R.drawable.flag_sx, "Sint Maarten", "+1721"),
    SLOVAKIA(R.drawable.flag_sk, "Slovakia", "+421"),
    SLOVENIA(R.drawable.flag_si, "Slovenia", "+386"),
    SOLOMON_ISLANDS(R.drawable.flag_sb, "Solomon Islands", "+677"),
    SOMALIA(R.drawable.flag_so, "Somalia", "+252"),
    SOUTH_AFRICA(R.drawable.flag_za, "South Africa", "+27"),
    SOUTH_KOREA(R.drawable.flag_kr, "South Korea", "+82"),
    SOUTH_SUDAN(R.drawable.flag_ss, "South Sudan", "+211"),
    SPAIN(R.drawable.flag_es, "Spain", "+34"),
    SRI_LANKA(R.drawable.flag_lk, "Sri Lanka", "+94"),
    SUDAN(R.drawable.flag_sd, "Sudan", "+249"),
    SURINAME(R.drawable.flag_sr, "Suriname", "+597"),
    SVALBARD_AND_JAN_MAYEN(R.drawable.flag_sj, "Svalbard and Jan Mayen", "+47"),
    SWAZILAND(R.drawable.flag_sz, "Swaziland", "+268"),
    SWEDEN(R.drawable.flag_se, "Sweden", "+46"),
    SWITZERLAND(R.drawable.flag_ch, "Switzerland", "+41"),
    SYRIA(R.drawable.flag_sy, "Syria", "+963"),
    TAIWAN(R.drawable.flag_tw, "Taiwan", "+886"),
    TAJIKISTAN(R.drawable.flag_tj, "Tajikistan", "+992"),
    TANZANIA(R.drawable.flag_tz, "Tanzania", "+255"),
    THAILAND(R.drawable.flag_th, "Thailand", "+66"),
    TOGO(R.drawable.flag_tg, "Togo", "+228"),
    TOKELAU(R.drawable.flag_tk, "Tokelau", "+690"),
    TONGA(R.drawable.flag_to, "Tonga", "+676"),
    TRINIDAD_AND_TOBAGO(R.drawable.flag_tt, "Trinidad and Tobago", "+1868"),
    TUNISIA(R.drawable.flag_tn, "Tunisia", "+216"),
    TURKEY(R.drawable.flag_tr, "Turkey", "+90"),
    TURKMENISTAN(R.drawable.flag_tm, "Turkmenistan", "+993"),
    TURKS_AND_CAICOS_ISLANDS(R.drawable.flag_tc, "Turks and Caicos Islands", "+1649"),
    TUVALU(R.drawable.flag_tv, "Tuvalu", "+688"),
    US_VIRGIN_ISLANDS(R.drawable.flag_vi, "U.S. Virgin Islands", "+1340"),
    UGANDA(R.drawable.flag_ug, "Uganda", "+256"),
    UKRAINE(R.drawable.flag_ua, "Ukraine", "+380"),
    UNITED_ARAB_EMIRATES(R.drawable.flag_ae, "United Arab Emirates", "+971"),
    UNITED_KINGDOM(R.drawable.flag_gb, "United Kingdom", "+44"),
    UNITED_STATES(R.drawable.flag_us, "United States", "+1"),
    URUGUAY(R.drawable.flag_uy, "Uruguay", "+598"),
    UZBEKISTAN(R.drawable.flag_uz, "Uzbekistan", "+998"),
    VANUATU(R.drawable.flag_vu, "Vanuatu", "+678"),
    VATICAN(R.drawable.flag_va, "Vatican", "+379"),
    VENEZUELA(R.drawable.flag_ve, "Venezuela", "+58"),
    VIETNAM(R.drawable.flag_vn, "Vietnam", "+84"),
    WALLIS_AND_FUTUNA(R.drawable.flag_wf, "Wallis and Futuna", "+681"),
    WESTERN_SAHARA(R.drawable.flag_eh, "Western Sahara", "+212"),
    YEMEN(R.drawable.flag_ye, "Yemen", "+967"),
    ZAMBIA(R.drawable.flag_zm, "Zambia", "+260"),
    ZIMBABWE(R.drawable.flag_zw, "Zimbabwe", "+263"),
}